<?php
function contenidoInforme($idinforme){
  include 'db_config.php';
  $mysqli=mysqli_connect($db_host,$db_user ,$db_password,$db_schema);
  $sentencia="SELECT id_user,id_mes,year FROM informes WHERE id=".$idinforme."";
  $stmt = mysqli_prepare($mysqli,$sentencia);
  mysqli_stmt_execute($stmt);
  mysqli_stmt_store_result($stmt);
  mysqli_stmt_bind_result($stmt,$idusuario,$mes,$year);
  mysqli_stmt_fetch($stmt);
  echo '<div class="form-group row">';
  echo '<label for="idmes" class="col-sm-3 col-form-label"><i class="fas fa-calendar"></i> Mes y año del informe </label>';
  echo '<input type="text" readonly class="col-sm-4 form-control" id="idmes" value="'.getMes($mes).' de '.$year.'"></div>';
  mysqli_stmt_close($stmt);
  $sentencia="SELECT respuesta FROM informes_text_content WHERE id_informe=".$idinforme."";
  $stmt = mysqli_prepare($mysqli,$sentencia);
  mysqli_stmt_execute($stmt);
  mysqli_stmt_store_result($stmt);
  mysqli_stmt_bind_result($stmt,$respuesta);
  $k=0;
  while(mysqli_stmt_fetch($stmt)){
    $respuestas[$k]=$respuesta;
    $k++;
  }
  mysqli_stmt_close($stmt);
  echo '<div class="form-group row">';
  echo nl2br("\n");
  echo '<label for="name" class="col-sm-3 col-form-label"><i class="fas fa-address-book"></i> Nombre completo </label>';
  echo nl2br("\n");
  echo '<p id="name" >'.getNombreyApellido($idusuario).'</p></div>';
  echo nl2br("\n");
  echo '<div class="form-group row">';
  echo nl2br("\n");
  echo '<label for="ciudad" class="col-sm-3 col-form-label"><i class="fas fa-map-marker-alt"></i> Ciudad </label>';
  echo nl2br("\n");
  echo '<p  id="ciudad">'.getCiudad($idusuario).'</p></div>';
  echo nl2br("\n");
  echo '<div class="form-group row">';
  echo nl2br("\n");
  echo '<label for="componente" class="col-sm-3 col-form-label"><i class="fas fa-briefcase"></i> Componente </label>';
  echo nl2br("\n");
  echo '<p id="componente">'.getComponente($idusuario).'</p></div>';
  echo nl2br("\n");
  echo '<div class="form-group row">';
  echo nl2br("\n");
  echo '<label for="coach" class="col-sm-3 col-form-label"><i class="fas fa-hands-helping"></i> Coach </label>';
  echo nl2br("\n");
  echo '<p id="coach"'.getCoach($idusuario).'"</p></div>';
  echo nl2br("\n");
  echo '<div class="alert alert-primary" role="alert" style="background-color:#007398;"><h4 style="color:white;font-weight:bold;">Primer esencial:  Generar y fomentar una cultura de oración y dependencia de Dios.</h4></div>';
  echo nl2br("\n");
  echo '<label for="pregunta1" class="col-sm-3 col-form-label"><p style="font-weight:bold;">¿Cómo estás cultivando tu relación con Dios?';
  echo ' ¿De que maneras estas viviendo tu vida en comunidad? (¿quién o quienes te cuidan? y ¿como?)</p></label>';
  echo nl2br("\n");
  echo '<p id="pregunta1">'.$respuestas[0].'</p>';
  echo nl2br("\n");
  echo '<label for="pregunta2" class="col-sm-3 col-form-label"><p style="font-weight:bold;">';
  echo '¿Qué hiciste que fomentó una cultura de oración en tu equipo?</p></label>';
  echo nl2br("\n");
  echo '<p  id="pregunta2">'.$respuestas[1].'</p>';
  echo nl2br("\n");
  echo '<div class="alert alert-primary" role="alert" style="background-color:#007398;"><h4 style="color:white;font-weight:bold;">';
  echo 'Segundo esencial:  Formarnos y capacitarnos como líderes de Cru.</h4></div>';
  echo nl2br("\n");
  echo '<label for="pregunta3" class="col-sm-3 col-form-label"><p style="font-weight:bold;">¿Preparaste las lecciones';
  echo ' de Formación de Nuevos Misioneros de este mes?, ¿De las sesiones de este mes de coaching en cuantas participaste?,';
  echo '¿Aplicaste lo aprendido en tu ministerio?, ¿Cómo? Cuéntanos lo más significativo en este mes de este y otros procesos deformación que estés llevando.</p></label>';
  echo nl2br("\n");
  echo '<p  id="pregunta3">'.$respuestas[2].'</p>';
  echo '<div class="alert alert-primary" role="alert" style="background-color:#3eb1c8;"><h4 style="color:white;font-weight:bold;">Tercer esencial:  Discipular y desarrollar un equipo de soporte misionero DDSM.</h4></div>';
  echo '<div class="form-group row"><label for="pregunta4" class="col-sm-3 col-form-label"><p style="font-weight:bold;">¿Este mes fue un tiempo concentrado de DDSM?</p></label>';
  echo '<p class="col-sm-1" id="pregunta4">'.$respuestas[3].'</p></div>';
  echo nl2br("\n");
  if($respuestas[3]==1){echo '<label for="pregunta5" class="col-sm-3 col-form-label"><p style="font-weight:bold;">';
  echo '¿Qué te enseñó Dios? ¿Cómo te ayudaron y ayudaste a tus líderes en el proceso del DDSM durante este mes?</p></label>';
  }
  if($respuestas[3]==2){echo '<label for="pregunta5" class="col-sm-3 col-form-label"><p style="font-weight:bold;">';
  echo '¿Qué te enseñó Dios? ¿Qué acciones tomaste con tu equipo ';
  echo 'relacionadas con la consecución de nuevos socios personales y de ciudad? ¿Cuantas citas de desafío a nuevos ';
  echo 'socios tuviste este mes? ¿Qué acciones tuviste con tus actuales socios que comunicaron, ';
  echo 'gratitud, visión y amor hacia ellos? ¿Qué acciones tomaste con tu equipo que comunicaron, ';
  echo 'gratitud, visión y amor hacia ellos?</p></label>';
  }
  echo nl2br("\n");
  echo '<p class="col-sm-8" id="pregunta5">'.$respuestas[4].'</p>';
  echo '<div class="alert alert-primary" role="alert" style="background-color:#f9b625;"><h4 style="color:white;font-weight:bold;">Cuarto esencial:  Discipulado y formación de otros.</h4></div>';
  echo nl2br("\n");
  echo '<p> Tomado del GMA, del área blanco del equipo bajo los criterios de LAC.</p>';
  echo '<p style="font-weight:bold;">Presentaciones del evangelio: '.$respuestas[5].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Decisiones en la presentación: '.$respuestas[6].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Seguimiento: '.$respuestas[7].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Discípulos multiplicadores:'.$respuestas[8].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Comunidades misionales: '.$respuestas[9].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Comunidades misionales catalíticas: '.$respuestas[10].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Personas que mantuvieron su fase: '.$respuestas[11].'</p>';
  echo nl2br("\n");
  echo '<p style="font-weight:bold;">Personas nuevas en cada fase: '.$respuestas[12].'</p>';
  echo '<p style="font-weight:bold;">Sus nombres: </p>';
  echo $respuestas[13];
  echo nl2br("\n");
  echo '<hr class="my-6">';
  echo nl2br("\n");
  echo '<center><h4>Tus discípulos</h4></center>';
  echo nl2br("\n");
  echo mostrarTablaDiscipulos($idusuario,$idinforme);
  echo '<hr class="my-6">';
  echo nl2br("\n");
  echo '<label for="pregunta15" class="col-sm-3 col-form-label"><p style="font-weight:bold;">';
  echo '¿Cómo está tu equipo supervisando regularmente que sus líderes estén formando discípulos multiplicadores?</p></label>';
  echo '<p class="col-sm-8 form-control" id="pregunta15">'.$respuestas[14].'</p>';
  echo nl2br("\n");
  echo '<div class="alert alert-primary" role="alert" style="background-color:#dd7d1b;"><h4 style="color:white;font-weight:bold;">Quinto esencial:  Formar un equipo de líderes.</h4></div>';
  echo nl2br("\n");
  echo '<label for="pregunta16" class="col-sm-3 col-form-label"><p style="font-weight:bold;"> ¿Qué has hecho para comunicar el propósito de tu equipo, la visión y misión en este mes? ';
  echo '¿Qué has hecho en este mes para desarrollar a cada miembro de tu Equipo de manera integral (personal, comunitaria y misional)?';
  echo '¿Qué acciones tomaron para mejorar los procesos claves del equipo? ¿Qué acciones tomó tu equipo este mes para movilizar nuevos voluntarios a involucrarse en la visión y misión?</p></label>';
  echo '<p class="col-sm-8 form-control" id="pregunta16">'.$respuestas[15].'</p>';
  echo nl2br("\n");
  echo '<label for="pregunta17" class="col-sm-3 col-form-label"><h3 style="font-weight:bold;">';
  echo '¿Hay algo significativo fuera de lo anteriormente preguntado que quieras compartirnos?</h3></label>';
  echo '<p class="col-sm-8 form-control" id="pregunta17">'.$respuestas[16].'</p>';
  mysqli_close($mysqli);
}
?>
